<#
.SYNOPSIS
    Sets up agent discovery for ADK web server

.DESCRIPTION
    This script creates the proper structure for ADK web server to discover all agents
    from subdirectories. It creates wrapper agent.py files at each Day level that
    expose all sub-agents, or creates a flat structure for discovery.

.PARAMETER Mode
    Discovery mode: 'wrapper' (creates wrapper files) or 'flat' (creates flat structure)
    Default: 'wrapper'

.PARAMETER Clean
    Remove previously created discovery files before setting up
#>

param(
    [ValidateSet('wrapper', 'flat')]
    [string]$Mode = 'wrapper',
    [switch]$Clean
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ScriptDir

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  ADK Agent Discovery Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Mode: $Mode" -ForegroundColor Cyan
Write-Host ""

# Function to find all agent.py files with root_agent
function Find-AgentFiles {
    param([string]$BaseDir)
    
    $agentFiles = @()
    $dirs = Get-ChildItem -Path $BaseDir -Directory -Recurse | Where-Object { 
        $_.Name -match '^Day\d+[ab]?$' -or $_.Name -notmatch '^(utility|__pycache__|\.)' 
    }
    
    foreach ($dir in $dirs) {
        $agentFile = Join-Path $dir.FullName "agent.py"
        if (Test-Path $agentFile) {
            # Check if file contains root_agent
            $content = Get-Content $agentFile -Raw
            if ($content -match 'root_agent\s*=') {
                $agentFiles += @{
                    Path = $agentFile
                    Directory = $dir.FullName
                    Name = $dir.Name
                    RelativePath = $agentFile.Replace($BaseDir + '\', '').Replace('\', '/')
                }
            }
        }
    }
    
    return $agentFiles
}

# Clean mode: Remove discovery files
if ($Clean) {
    Write-Host "Cleaning previous discovery files..." -ForegroundColor Yellow
    
    # Remove wrapper files
    Get-ChildItem -Path $ScriptDir -Recurse -Filter "agent.py" | Where-Object {
        $_.FullName -match '\\Day\d+[ab]?\\agent\.py$' -and 
        $_.FullName -notmatch '\\helpful_assistant\\' -and
        $_.FullName -notmatch '\\sample-agent\\'
    } | Remove-Item -Force
    
    # Remove flat structure
    if (Test-Path (Join-Path $ScriptDir "agents")) {
        Remove-Item -Path (Join-Path $ScriptDir "agents") -Recurse -Force
    }
    
    Write-Host "Cleanup complete." -ForegroundColor Green
    Write-Host ""
}

# Find all agents
Write-Host "Discovering agents..." -ForegroundColor Cyan
$agents = Find-AgentFiles -BaseDir $ScriptDir

Write-Host "Found $($agents.Count) agents:" -ForegroundColor Green
foreach ($agent in $agents) {
    Write-Host "  - $($agent.RelativePath)" -ForegroundColor Gray
}
Write-Host ""

if ($Mode -eq 'wrapper') {
    Write-Host "Creating wrapper agent.py files..." -ForegroundColor Cyan
    
    # Group agents by Day directory
    $dayGroups = @{}
    foreach ($agent in $agents) {
        $dayMatch = [regex]::Match($agent.RelativePath, '^(Day\d+[ab]?)/')
        if ($dayMatch.Success) {
            $dayName = $dayMatch.Groups[1].Value
            if (-not $dayGroups.ContainsKey($dayName)) {
                $dayGroups[$dayName] = @()
            }
            $dayGroups[$dayName] += $agent
        }
    }
    
    # Create wrapper files for each Day
    foreach ($dayName in $dayGroups.Keys) {
        $dayPath = Join-Path $ScriptDir $dayName
        $wrapperFile = Join-Path $dayPath "agent.py"
        
        # Skip if wrapper already exists and is not a discovery wrapper
        if (Test-Path $wrapperFile) {
            $content = Get-Content $wrapperFile -Raw
            if ($content -match '# ADK Discovery Wrapper') {
                Write-Host "  Updating wrapper: $dayName/agent.py" -ForegroundColor Yellow
            } else {
                Write-Host "  Skipping $dayName/agent.py (already exists, not a wrapper)" -ForegroundColor Yellow
                continue
            }
        }
        
        Write-Host "  Creating wrapper: $dayName/agent.py" -ForegroundColor Green
        
        $wrapperContent = @"
# ADK Discovery Wrapper
# This file makes all agents in $dayName discoverable by ADK web server
# Auto-generated by setup-adk-discovery.ps1

import sys
from pathlib import Path

# Add parent directory to path
parent_dir = Path(__file__).parent.parent
sys.path.insert(0, str(parent_dir))

# Import the first agent found (ADK expects one root_agent per directory)
# For multiple agents, use the first one or create a router agent

"@
        
        # Import the first agent as root_agent
        $firstAgent = $dayGroups[$dayName][0]
        $relativeImport = $firstAgent.RelativePath.Replace('.py', '').Replace('/', '.')
        
        $wrapperContent += @"
try:
    from $relativeImport import root_agent
    # root_agent is now available for ADK discovery
except ImportError as e:
    print(f"Warning: Could not import agent from $relativeImport : {e}")
    # Create a fallback agent
    from google.adk.agents import Agent
    from google.adk.models.google_llm import Gemini
    root_agent = Agent(
        name="$dayName",
        model=Gemini(model="gemini-2.5-flash-lite"),
        description="Wrapper agent for $dayName - import failed",
        instruction="This is a wrapper agent. The actual agent could not be loaded."
    )
"@
        
        $wrapperContent | Out-File -FilePath $wrapperFile -Encoding utf8
    }
    
    Write-Host ""
    Write-Host "Wrapper files created!" -ForegroundColor Green
    
} elseif ($Mode -eq 'flat') {
    Write-Host "Creating flat structure..." -ForegroundColor Cyan
    
    $agentsDir = Join-Path $ScriptDir "agents"
    if (-not (Test-Path $agentsDir)) {
        New-Item -ItemType Directory -Path $agentsDir | Out-Null
    }
    
    foreach ($agent in $agents) {
        $agentName = $agent.Name
        $targetDir = Join-Path $agentsDir $agentName
        
        if (-not (Test-Path $targetDir)) {
            New-Item -ItemType Directory -Path $targetDir | Out-Null
        }
        
        # Copy agent.py
        $targetFile = Join-Path $targetDir "agent.py"
        Copy-Item -Path $agent.Path -Destination $targetFile -Force
        
        # Copy __init__.py if exists
        $initFile = Join-Path $agent.Directory "__init__.py"
        if (Test-Path $initFile) {
            Copy-Item -Path $initFile -Destination (Join-Path $targetDir "__init__.py") -Force
        }
        
        Write-Host "  Created: agents/$agentName/agent.py" -ForegroundColor Green
    }
    
    Write-Host ""
    Write-Host "Flat structure created in 'agents' directory!" -ForegroundColor Green
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

if ($Mode -eq 'wrapper') {
    Write-Host "To run ADK web server:" -ForegroundColor Cyan
    Write-Host "  cd kaggle-5-day-agents" -ForegroundColor White
    Write-Host "  adk web ." -ForegroundColor White
    Write-Host ""
    Write-Host "This will discover agents in Day1a, Day1b, etc." -ForegroundColor Gray
} else {
    Write-Host "To run ADK web server:" -ForegroundColor Cyan
    Write-Host "  cd kaggle-5-day-agents" -ForegroundColor White
    Write-Host "  adk web agents" -ForegroundColor White
    Write-Host ""
    Write-Host "This will discover all agents from the flat structure." -ForegroundColor Gray
}

Write-Host ""


