"""
A2A Server for helpful_assistant

This module exposes the helpful_assistant via the A2A (Agent-to-Agent) protocol,
allowing other agents to communicate with it over HTTP.

Auto-generated by a2a_generator.py
"""

import os
import sys
from pathlib import Path

# Add parent directories to path
sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent))

# Load environment variables
from dotenv import load_dotenv
capstone_root = Path(__file__).resolve()
# Try to find .env going up the directory tree
for i in range(5):
    capstone_root = capstone_root.parent
    env_path = capstone_root / '.env'
    if env_path.exists():
        load_dotenv(dotenv_path=env_path)
        break

# Set service account path if exists
service_account_path = capstone_root / 'service_account.json'
if service_account_path.exists():
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = str(service_account_path.absolute())

# Import the agent
from agent import root_agent

# Import A2A utilities
try:
    from google.adk.a2a.utils.agent_to_a2a import to_a2a
except ImportError:
    print("Error: google.adk.a2a not available. Please update google-adk package.")
    print("Run: pip install --upgrade google-adk")
    sys.exit(1)

# Port configuration
A2A_PORT = int(os.environ.get("HELPFUL_ASSISTANT_A2A_PORT", "10101"))

# Create the A2A application
print(f"🚀 Starting helpful_assistant A2A Server on port {A2A_PORT}")
a2a_app = to_a2a(root_agent, port=A2A_PORT)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(a2a_app, host="0.0.0.0", port=A2A_PORT)
