# ADK Discovery Wrapper
# This file makes all agents in Day1a discoverable by ADK web server
# Auto-generated by setup-adk-discovery.ps1

import sys
from pathlib import Path

# Add parent directory to path
parent_dir = Path(__file__).parent.parent
sys.path.insert(0, str(parent_dir))

# Import the first agent found (ADK expects one root_agent per directory)
# For multiple agents, use the first one or create a router agent
try:
    from Day1a.helpful_assistant.agent import root_agent
    # root_agent is now available for ADK discovery
except ImportError as e:
    print(f"Warning: Could not import agent from Day1a.helpful_assistant.agent : {e}")
    # Create a fallback agent
    from google.adk.agents import Agent
    from google.adk.models.google_llm import Gemini
    root_agent = Agent(
        name="Day1a",
        model=Gemini(model="gemini-2.5-flash-lite"),
        description="Wrapper agent for Day1a - import failed",
        instruction="This is a wrapper agent. The actual agent could not be loaded."
    )
